import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Footer from "@/components/Footer";
//import { AuthProvider } from "@/app/lib/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* <AuthProvider> */}
          <SideBar>
            <main className="flex-grow">
              {children}
            </main>
          </SideBar>
          <Footer />
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
